name: Scan my code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
   scan:
     runs-on: ubuntu-latest
     name: Verracode Container/IaC/Secrets scan
     steps:
         - name: checkout
           uses: actions/checkout@v3

         - name: Verracode Container/IaC/Secrets action step1
           uses: veracode/container_iac_secrets_scanning@v1.0.0
           with:
             vid: ${{ secrets.VID }}
             vkey: ${{ secrets.VKEY }}
             command: "scan" 
             type: "directory"
             source: "./"
             format: "json"
             debug: false
             fail_build: true
